<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputPath>artifacts/bin/</OutputPath>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(FishingModRoot)/Source/Contracts/*.cs"/>
    <Compile Include="$(FishingModRoot)/Source/Content/*.cs"/>
    <Compile Include="ContentTests.cs"/>
  </ItemGroup>
</Project>
