using System;using System.IO;using System.Linq;using UnityEngine;using HarmonyLib;using PZAEC.Mecha;
public sealed class JusticeNativeQA:IModApi {
 public void InitMod(Mod m){if(Environment.GetCommandLineArgs().Contains("-mechaMotionQA"))ModEvents.GameStartDone.RegisterHandler(Run);}
 static bool Pause(){return false;}
 static void Run(ref ModEvents.SGameStartDoneData data){int fail=0;try{
 var h=new Harmony("justice.preview");h.Patch(AccessTools.Method(typeof(Weapons),"Update"),prefix:new HarmonyMethod(typeof(JusticeNativeQA),nameof(Pause)));
 var w=GameManager.Instance.World;AccessTools.Field(typeof(Weapons),"currentWorld").SetValue(null,w);
 var v=EntityFactory.CreateEntity(EntityClass.FromString(Rules.CompleteVehicle),new Vector3(0,400,0)+Origin.position) as EntityVehicle;w.SpawnEntityInWorld(v);v.vehicle.SetItemValue(ItemClass.GetItem(Rules.CompleteItem,false));for(var t=v.vehicleRB.transform;t!=null;t=t.parent)t.gameObject.SetActive(true);v.vehicleRB.isKinematic=true;
 var r=Model.GetRig(v);r.ResetPose();Justice.Walk(v,r,0,0,.02f);Justice.Combat(v,r,Samurai.Get(v),Time.time);Log.Out("[JusticeQA] board="+Boarding.Active(v)+" gun="+Samurai.Get(v).LaserCharge+" justice="+r.Justice.Parts.Length);foreach(var p in r.Justice.Parts)Log.Out("[JusticeQA] "+p.name+" enabled="+p.enabled);
 var dir=Path.Combine(GameIO.GetSaveGameDir(),"justice-review");Directory.CreateDirectory(dir);
 var camera=new GameObject("Justice camera").AddComponent<Camera>();var rt=new RenderTexture(960,960,24);camera.targetTexture=rt;camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.12f,.15f,.19f);camera.fieldOfView=40;camera.cullingMask=1<<30;
 var lamp=new GameObject("Justice key").AddComponent<Light>();lamp.type=LightType.Directional;lamp.intensity=1.2f;lamp.transform.rotation=Quaternion.Euler(35,-25,0);lamp.cullingMask=1<<30;RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Flat;RenderSettings.ambientLight=Color.gray;var sh=new UnityEngine.Rendering.SphericalHarmonicsL2();sh.AddAmbientLight(Color.gray);RenderSettings.ambientProbe=sh;
 var baked=new System.Collections.Generic.List<GameObject>();foreach(var skin in r.Justice.Parts){if(!skin.enabled||!skin.gameObject.activeSelf)continue;var s=(SkinnedMeshRenderer)skin;var mesh=new Mesh();s.BakeMesh(mesh);var o=new GameObject(s.name);baked.Add(o);o.layer=30;o.transform.SetPositionAndRotation(s.transform.position,s.transform.rotation);o.transform.localScale=s.transform.lossyScale;o.AddComponent<MeshFilter>().sharedMesh=mesh;o.AddComponent<MeshRenderer>().sharedMaterial=s.sharedMaterial;s.enabled=false;}
 r.Visual.gameObject.SetActive(false);var focus=r.Mount.position+Vector3.up*1.7f;int i=0;foreach(var offset in new[]{new Vector3(0,.4f,6.7f),new Vector3(6.7f,.4f,0),new Vector3(0,.4f,-6.7f),new Vector3(-6.7f,.4f,0)}){camera.transform.position=focus+offset;camera.transform.LookAt(focus);camera.Render();RenderTexture.active=rt;var png=new Texture2D(960,960,TextureFormat.RGB24,false);png.ReadPixels(new Rect(0,0,960,960),0,0);png.Apply();File.WriteAllBytes(Path.Combine(dir,"view-"+(i++)+".png"),png.EncodeToPNG());UnityEngine.Object.DestroyImmediate(png);}
 foreach(var part in baked){foreach(var o in baked)o.SetActive(o==part);camera.transform.position=focus+new Vector3(0,.4f,6.7f);camera.transform.LookAt(focus);camera.Render();RenderTexture.active=rt;var png=new Texture2D(960,960,TextureFormat.RGB24,false);png.ReadPixels(new Rect(0,0,960,960),0,0);png.Apply();File.WriteAllBytes(Path.Combine(dir,part.name+".png"),png.EncodeToPNG());UnityEngine.Object.DestroyImmediate(png);}
 Log.Out("[JusticeQA] renders="+dir);Log.Out("[JusticeQA] feet="+r.FootL.position+" "+r.FootR.position);
 }catch(Exception e){fail++;Log.Error("[JusticeQA] "+e);}Log.Out("[MechaMotionQA] COMPLETE failures="+fail);}
}
