using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using PZAEC.Mecha;
public sealed class JusticeCombatNativeQA:IModApi {
 static int failures;static List<string> lines=new List<string>();
 public void InitMod(Mod m){if(Environment.GetCommandLineArgs().Contains("-mechaMotionQA"))ModEvents.GameStartDone.RegisterHandler(Run);}
 static void Check(string label,bool pass){lines.Add((pass?"PASS ":"FAIL ")+label);if(!pass)failures++;}
 static void Run(ref ModEvents.SGameStartDoneData d){try{var w=GameManager.Instance.World;var v=EntityFactory.CreateEntity(EntityClass.FromString(Rules.CompleteVehicle),new Vector3(0,400,0)+Origin.position) as EntityVehicle;w.SpawnEntityInWorld(v);v.vehicle.SetItemValue(ItemClass.GetItem(Rules.CompleteItem,false));for(var t=v.vehicleRB.transform;t!=null;t=t.parent)t.gameObject.SetActive(true);v.vehicleRB.isKinematic=true;var r=Model.GetRig(v);var s=Samurai.Get(v);
 Check("65 bones and four influences",r.Justice.Bones.Length==65&&r.Justice.Parts.All(p=>((SkinnedMeshRenderer)p).quality==SkinQuality.Bone4));
 foreach(bool heavy in new[]{false,true})foreach(int combo in new[]{0,1}){int blocked=0;float drift=0,grip=0;for(int i=0;i<=90;i++){r.ResetPose();Justice.Walk(v,r,0,0,.02f);s.Swing=true;s.Heavy=heavy;s.Combo=combo;s.Started=Time.time-i*(heavy?Samurai.HeavyDuration:Samurai.NormalDuration)/90;Justice.Combat(v,r,s,Time.time);var tipBeforeWeight=SwordMotion.Tip(r);var finish=typeof(Justice).Assembly.GetType("PZAEC.Mecha.JusticeFinish");if(finish!=null){float phase=SwordMotion.Phase(s,Time.time);if(phase>=SwordMotion.WindEnd&&phase<=SwordMotion.CutEnd){finish.GetMethod("Weight").Invoke(null,new object[]{v,r,.02f});Justice.Combat(v,r,s,Time.time);if(Vector3.Distance(tipBeforeWeight,SwordMotion.Tip(r))>.0001f)throw new Exception("Polish changed the active cut trajectory");}}if(!Justice.BladeClear(r))blocked++;grip=Mathf.Max(grip,Vector3.Distance(r.Sword.position,r.HandR.position));var tip=SwordMotion.Tip(r);SwordMotion.Pose(v,r,s,Time.time);drift=Mathf.Max(drift,Vector3.Distance(tip,SwordMotion.Tip(r)));}
 Check("sword heavy="+heavy+" combo="+combo+" deterministic drift="+drift,drift<.001f);Check("sword mounted grip distance="+grip,grip<.2f);Check("sword body clearance blocked frames="+blocked,blocked==0);}
 s.Swing=false;s.LaserCharge=1;r.ResetPose();Justice.Combat(v,r,s,Time.time);Check("rifle replaces sword",r.Justice.Parts.Where((p,i)=>r.Justice.Roles[i]=="Weapon64").All(p=>p.gameObject.activeSelf)&&r.Justice.Parts.Where((p,i)=>r.Justice.Roles[i]=="Weapon54").All(p=>!p.gameObject.activeSelf));Check("rifle muzzle finite",Weapons.Finite(r.Justice.GunMuzzle.position.x)&&Vector3.Distance(r.HandR.position,r.Justice.GunMuzzle.position)<2.5f);
 s.LaserCharge=0;s.Guarding=true;s.GuardBlend=0;r.ResetPose();Samurai.Pose(v,r,.11f,Time.time);Check("guard raises progressively",Mathf.Abs(s.GuardBlend-.5f)<.001f);s.Guarding=false;Samurai.Pose(v,r,.11f,Time.time);Check("guard returns progressively",s.GuardBlend==0);s.Guarding=true;r.ResetPose();Justice.Combat(v,r,s,Time.time);Check("shield remains visible",r.Justice.Parts.Where((p,i)=>r.Justice.Roles[i]=="Weapon63").All(p=>p.gameObject.activeSelf));r.ResetPose();Check("scale restored after combat",r.Justice.Bones.Select((b,i)=>(b.localScale-r.Justice.BaseScale[i]).sqrMagnitude).All(x=>x<.000001f));
 s.Guarding=false;s.LaserCharge=1;r.ResetPose();Justice.Combat(v,r,s,Time.time);r.ResetPose();Justice.Board(r,1);Check("boarding clears rifle and beam visibility",r.Justice.Parts.Where((p,i)=>r.Justice.Roles[i]=="Weapon64"||r.Justice.Roles[i]=="Weapon54").All(p=>!p.gameObject.activeSelf));Check("boarding kneels without moving physical root",Mathf.Abs((r.Torso.localPosition-r.TorsoBasePosition).y+.45f)<.001f&&Mathf.Abs(v.vehicleRB.position.y-400)<.001f);s.RifleBlend=s.GuardBlend=1;Samurai.Stop(v);Check("boarding stop clears presentation blends",s.RifleBlend==0&&s.GuardBlend==0);
 }catch(Exception e){Check("exception "+e,false);}var path=Path.Combine(GameIO.GetSaveGameDir(),"justice-combat-qa.txt");File.WriteAllLines(path,lines);foreach(var l in lines)Log.Out("[JusticeCombatQA] "+l);Log.Out("[MechaMotionQA] COMPLETE failures="+failures+" report="+path);}
}
