using System;using System.IO;using System.Linq;using UnityEngine;using HarmonyLib;using PZAEC.Mecha;
// Isolated native-engine scripted review, explicitly not a human driving recording.
public sealed class JusticeVideoQA:IModApi {
 static Camera cam;static RenderTexture rt;static Model.Rig rig;static EntityVehicle v;static World world;static string folder;static GameObject[] copies;static Mesh[] meshes;
 public void InitMod(Mod m){if(Environment.GetCommandLineArgs().Contains("-mechaMotionQA"))ModEvents.GameStartDone.RegisterHandler(Run);}
 static bool Pause(){return false;}
 static void Capture(string name,int frame,Vector3 offset,bool fp=false,float focusHeight=1.7f){
 for(int i=0;i<copies.Length;i++){var skin=(SkinnedMeshRenderer)rig.Justice.Parts[i];copies[i].SetActive(skin.gameObject.activeSelf&&(!fp||skin.GetComponent<MechaRenderPart>().FirstPersonVisible));skin.BakeMesh(meshes[i]);copies[i].transform.SetPositionAndRotation(skin.transform.position,skin.transform.rotation);copies[i].transform.localScale=skin.transform.lossyScale;}
 var focus=rig.Mount.position+Vector3.up*focusHeight;cam.transform.position=fp?Optics.CameraPosition(v,rig,rig.Mount.rotation,false):focus+offset*1.5f;if(fp)cam.transform.rotation=rig.Mount.rotation;else cam.transform.LookAt(focus);cam.Render();RenderTexture.active=rt;var image=new Texture2D(rt.width,rt.height,TextureFormat.RGB24,false);image.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);image.Apply();File.WriteAllBytes(Path.Combine(folder,name+"-"+frame.ToString("D4")+".png"),image.EncodeToPNG());UnityEngine.Object.DestroyImmediate(image);
 }
 static void Reset(){var rb=v.vehicleRB;rig.ResetPose();Gait.Forget(v);GroundSupport.Forget(v);Traversal.Forget(v);var support=GroundSupport.Get(v);rb.position=new Vector3(0,400+support.Shape.NeutralY+Rules.SoleClearance,0);rb.rotation=Quaternion.identity;rb.velocity=rb.angularVelocity=Vector3.zero;v.SetPosition(rb.position+Origin.position);var s=Locomotion.Get(v);s.SkimPhase=Skim.Phase.Off;s.FlightMode=Flight.Phase.Ground;s.Grounded=true;s.Blend=s.WingBlend=0;s.SkimLatch=false;Physics.SyncTransforms();Samurai.Stop(v);}
 static void Walk(float speed,float turn,float dt){var rb=v.vehicleRB;var s=GroundSupport.Observe(v);s.DesiredVelocity=rb.rotation*Vector3.forward*speed;speed=Traversal.LimitSpeed(v,s,speed,dt);GroundSupport.Walking(s,dt,true);if(!GroundSupport.MotionClear(s,dt)){GroundSupport.StopHorizontal(s);speed=0;}GroundSupport.Apply(s,dt);if(s.Grounded)Locomotion.ApplyDrive(rb,rb.rotation*Vector3.forward,Mathf.Clamp(speed,-s.DriveCap,s.DriveCap),turn,false,s.Normal,dt);Physics.Simulate(dt);v.SetPosition(rb.position+Origin.position);Physics.SyncTransforms();Locomotion.Get(v).Grounded=s.Grounded;Gait.Update(world,v,rig,dt);}
 static void Run(ref ModEvents.SGameStartDoneData data){bool automatic=Physics.autoSimulation;Physics.autoSimulation=false;int fail=0;try{
 var h=new Harmony("justice.video.qa");h.Patch(AccessTools.Method(typeof(Weapons),"Update"),prefix:new HarmonyMethod(typeof(JusticeVideoQA),nameof(Pause)));world=GameManager.Instance.World;AccessTools.Field(typeof(Weapons),"currentWorld").SetValue(null,world);
 v=EntityFactory.CreateEntity(EntityClass.FromString(Rules.CompleteVehicle),new Vector3(0,400,0)+Origin.position) as EntityVehicle;world.SpawnEntityInWorld(v);v.vehicle.SetItemValue(ItemClass.GetItem(Rules.CompleteItem,false));v.vehicle.SetFuelLevel(100);v.hasDriver=v.IsEngineRunning=true;var rb=v.vehicleRB;for(var t=rb.transform;t!=null;t=t.parent)t.gameObject.SetActive(true);rb.isKinematic=false;rb.useGravity=true;rb.drag=0;rig=Model.GetRig(v);
 var floor=GameObject.CreatePrimitive(PrimitiveType.Cube);floor.transform.position=new Vector3(0,399.5f,80);floor.transform.localScale=new Vector3(300,1,400);floor.layer=16;var floorPicture=GameObject.CreatePrimitive(PrimitiveType.Cube);UnityEngine.Object.DestroyImmediate(floorPicture.GetComponent<Collider>());floorPicture.transform.SetParent(floor.transform,false);floorPicture.layer=30;floor.GetComponent<Renderer>().enabled=false;floorPicture.GetComponent<Renderer>().sharedMaterial=new Material(Shader.Find("Standard")){color=new Color(.23f,.26f,.28f)};
 cam=new GameObject("Justice review camera").AddComponent<Camera>();rt=new RenderTexture(960,960,24);cam.targetTexture=rt;cam.fieldOfView=40;cam.cullingMask=1<<30;cam.clearFlags=CameraClearFlags.SolidColor;cam.backgroundColor=new Color(.12f,.15f,.19f);
 var light=new GameObject("Justice review key").AddComponent<Light>();light.type=LightType.Directional;light.intensity=1.4f;light.transform.rotation=Quaternion.Euler(40,-35,0);light.cullingMask=1<<30;RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Flat;RenderSettings.ambientLight=Color.gray;var sh=new UnityEngine.Rendering.SphericalHarmonicsL2();sh.AddAmbientLight(Color.gray);RenderSettings.ambientProbe=sh;
 foreach(var tr in rig.Mount.GetComponentsInChildren<Transform>(true))tr.gameObject.layer=30;copies=new GameObject[rig.Justice.Parts.Length];meshes=new Mesh[copies.Length];for(int i=0;i<copies.Length;i++){var skin=rig.Justice.Parts[i];skin.gameObject.layer=0;copies[i]=new GameObject("Review "+skin.name);copies[i].layer=30;meshes[i]=new Mesh();copies[i].AddComponent<MeshFilter>().sharedMesh=meshes[i];copies[i].AddComponent<MeshRenderer>().sharedMaterial=skin.sharedMaterial;}
 folder=Path.Combine(GameIO.GetSaveGameDir(),"justice-videos");Directory.CreateDirectory(folder);Reset();for(int i=0;i<30;i++)Walk(0,0,1f/30);int view=0;foreach(var offset in new[]{new Vector3(0,.4f,6.8f),new Vector3(6.8f,.4f,0),new Vector3(0,.4f,-6.8f),new Vector3(-6.8f,.4f,0)})Capture("preview",view++,offset);Capture("first-person",0,Vector3.zero,true);light.intensity=.05f;var night=new UnityEngine.Rendering.SphericalHarmonicsL2();night.AddAmbientLight(new Color(.04f,.04f,.07f));RenderSettings.ambientProbe=night;Capture("night",0,new Vector3(4,.6f,6));light.intensity=1.4f;RenderSettings.ambientProbe=sh;
 for(int i=0;i<180;i++){Walk(i<80?4:i<120?-2:0,i>=140?1:0,1f/30);Capture("walk",i,new Vector3(4,.6f,6));}
 Reset();for(int i=0;i<210;i++){Walk(i<90?1.2f:i<150?4:0,i>=170?1:0,1f/30);Capture("legs-front",i,new Vector3(0,.05f,3),false,.8f);Capture("legs-side",i,new Vector3(3,.05f,0),false,.8f);}
 Reset();var m=Locomotion.Get(v);for(int i=0;i<240;i++){Skim.Drive(v,m,i==0,i<150,i<150?1:0,0,true,1f/30);Physics.Simulate(1f/30);v.SetPosition(rb.position+Origin.position);Physics.SyncTransforms();Gait.Update(world,v,rig,1f/30);Capture("skim",i,new Vector3(4,.6f,6));}
 Reset();for(int i=0;i<210;i++){bool ground=i==0||rb.position.y<=400.03f;Flight.Advance(m,true,i==0||i==110,ground,0,v.position.y,1f/30);m.Grounded=ground;m.WingBlend=Mathf.MoveTowards(m.WingBlend,Flight.AirPose(m)?1:0,1f/30);if(Flight.Active(m)){GroundSupport.Suspend(v);float vertical=m.FlightMode==Flight.Phase.Landing?-.8f:Mathf.Clamp((402-rb.position.y)*3,-2,2);Flight.ApplyControl(rb,i>50&&i<110?4:0,0,false,vertical,1f/30);Physics.Simulate(1f/30);v.SetPosition(rb.position+Origin.position);Gait.Update(world,v,rig,1f/30);}else Walk(0,0,1f/30);Capture("flight",i,new Vector3(4,.6f,6));}
 Reset();for(int i=0;i<240;i++){var s=Samurai.Get(v);s.Swing=i<80||(i>=104&&i<148);s.Heavy=i>=104&&i<148;s.Combo=i<40?0:1;s.Started=Time.time-(i<40?i:i<80?i-40:i-104)/30f;s.Charging=i>=80&&i<104;s.PressedAt=Time.time-(i-80)/30f;s.Guarding=i>=148&&i<180;s.LaserCharge=i>=180?Mathf.Clamp01((i-180)/18f):0;Walk(0,0,1f/30);Capture("combat",i,new Vector3(4,.6f,6));if(i==210)Capture("first-person-rifle",0,Vector3.zero,true);}
 Reset();for(int settle=0;settle<30;settle++)Walk(0,0,1f/30);for(int i=0;i<180;i++){rig.ResetPose();float kneel=(1-Mathf.Cos(i/179f*Mathf.PI*2))*.5f;Justice.Board(rig,kneel);var support=GroundSupport.Get(v);for(int side=0;side<2;side++){Gait.Solve(rig,side,support.Feet[side].Position-Origin.position,Vector3.up);if(Vector3.Distance((side==0?rig.FootL:rig.FootR).position+Origin.position,support.Feet[side].Position)>.02f)throw new Exception("Boarding pose foot contact lost");}Capture("boarding",i,new Vector3(4,.6f,6));}
 File.WriteAllText(Path.Combine(folder,"recording-context.txt"),"Scripted isolated native Unity/PhysX review. Walk and skim use production ground/skim controllers; Q sequence injects flight commands; combat injects authoritative pose states, without live target hits. Boarding is a crouch/stand pose review, not the seat-interaction sequence. Not human driving, not two-client networking, not save reload acceptance.");Log.Out("[JusticeVideoQA] output="+folder);
 }catch(Exception e){fail++;Log.Error("[JusticeVideoQA] "+e);}finally{Physics.autoSimulation=automatic;}Log.Out("[MechaMotionQA] COMPLETE failures="+fail);}
}
