using System;using System.IO;using System.Linq;using UnityEngine;using HarmonyLib;using PZAEC.Mecha;
public sealed class NuNativeQA:IModApi {
 public void InitMod(Mod m){if(Environment.GetCommandLineArgs().Contains("-mechaMotionQA"))ModEvents.GameStartDone.RegisterHandler(Run);}
 static bool Pause(){return false;}
 static void Run(ref ModEvents.SGameStartDoneData data){int fail=0;try{
 var h=new Harmony("justice.preview");h.Patch(AccessTools.Method(typeof(Weapons),"Update"),prefix:new HarmonyMethod(typeof(NuNativeQA),nameof(Pause)));
 var w=GameManager.Instance.World;AccessTools.Field(typeof(Weapons),"currentWorld").SetValue(null,w);
 var v=EntityFactory.CreateEntity(EntityClass.FromString(Rules.UltimateVehicle),new Vector3(0,400,0)+Origin.position) as EntityVehicle;w.SpawnEntityInWorld(v);v.vehicle.SetItemValue(ItemClass.GetItem(Rules.UltimateItem,false));for(var t=v.vehicleRB.transform;t!=null;t=t.parent)t.gameObject.SetActive(true);v.vehicleRB.isKinematic=true;
 var r=Model.GetRig(v);
 if(!Rules.Complete(v)||!Rules.Ultimate(v)||Rules.DisplayName(v)!="初号机（究极体）")throw new Exception("variant routing");
 if(r.Justice.Document.bones.Length!=124)throw new Exception("Nu bones");
 var full=EntityFactory.CreateEntity(EntityClass.FromString(Rules.CompleteVehicle),new Vector3(20,400,0)+Origin.position) as EntityVehicle;w.SpawnEntityInWorld(full);full.vehicle.SetItemValue(ItemClass.GetItem(Rules.CompleteItem,false));var fr=Model.GetRig(full);
 if(fr.Justice.Ultimate||fr.Justice.Document.bones.Length!=65||fr.Justice.Document==r.Justice.Document)throw new Exception("mixed chassis data");
 r.ResetPose();Justice.Walk(v,r,0,0,.02f);Justice.Combat(v,r,Samurai.Get(v),Time.time);if(Mathf.Abs(Vector3.Distance(SwordMotion.Root(r),SwordMotion.Tip(r))-1.52f)>.02f)throw new Exception("blade anchor scale");Log.Out("[JusticeQA] board="+Boarding.Active(v)+" gun="+Samurai.Get(v).LaserCharge+" justice="+r.Justice.Parts.Length);foreach(var p in r.Justice.Parts)Log.Out("[JusticeQA] "+p.name+" enabled="+p.enabled);
 var dir=Path.Combine(GameIO.GetSaveGameDir(),"nu-review");Directory.CreateDirectory(dir);
 var camera=new GameObject("Justice camera").AddComponent<Camera>();var rt=new RenderTexture(960,960,24);camera.targetTexture=rt;camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.12f,.15f,.19f);camera.fieldOfView=40;camera.cullingMask=1<<30;
 var lamp=new GameObject("Justice key").AddComponent<Light>();lamp.type=LightType.Directional;lamp.intensity=1.2f;lamp.transform.rotation=Quaternion.Euler(35,-25,0);lamp.cullingMask=1<<30;RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Flat;RenderSettings.ambientLight=Color.gray;var sh=new UnityEngine.Rendering.SphericalHarmonicsL2();sh.AddAmbientLight(Color.gray);RenderSettings.ambientProbe=sh;var studioReflection=new Cubemap(16,TextureFormat.RGBAHalf,true);for(int face=0;face<6;face++){var pixels=new Color[256];float brightness=face==2?.72f:face==3?.18f:.48f;for(int pixel=0;pixel<pixels.Length;pixel++)pixels[pixel]=new Color(brightness,brightness,brightness,1);studioReflection.SetPixels(pixels,(CubemapFace)face);}studioReflection.Apply(true,false);RenderSettings.defaultReflectionMode=UnityEngine.Rendering.DefaultReflectionMode.Custom;RenderSettings.customReflection=studioReflection;RenderSettings.reflectionIntensity=1;
 var baked=new System.Collections.Generic.List<GameObject>();foreach(var skin in r.Justice.Parts){if(!skin.enabled||!skin.gameObject.activeSelf)continue;var s=(SkinnedMeshRenderer)skin;var mesh=new Mesh();s.BakeMesh(mesh);if(mesh.bounds.size.magnitude>8)throw new Exception("Nu mesh exploded "+s.name+" "+mesh.bounds);var o=new GameObject(s.name);baked.Add(o);o.layer=30;o.transform.SetPositionAndRotation(s.transform.position,s.transform.rotation);o.transform.localScale=s.transform.lossyScale;o.AddComponent<MeshFilter>().sharedMesh=mesh;o.AddComponent<MeshRenderer>().sharedMaterial=s.sharedMaterial;s.enabled=false;}
 r.Visual.gameObject.SetActive(false);var focus=r.Mount.position+Vector3.up*1.7f;int i=0;foreach(var offset in new[]{new Vector3(1.7f,.4f,7.4f),new Vector3(7.4f,.4f,0),new Vector3(0,.4f,-7.4f),new Vector3(-6.7f,.4f,0)}){camera.transform.position=focus+offset;camera.transform.LookAt(focus);camera.Render();RenderTexture.active=rt;var png=new Texture2D(960,960,TextureFormat.RGB24,false);png.ReadPixels(new Rect(0,0,960,960),0,0);png.Apply();File.WriteAllBytes(Path.Combine(dir,"view-"+(i++)+".png"),png.EncodeToPNG());UnityEngine.Object.DestroyImmediate(png);}
 var iconRt=new RenderTexture(256,256,24);camera.targetTexture=iconRt;camera.backgroundColor=Color.clear;camera.transform.position=focus+new Vector3(1.7f,.4f,6f);camera.transform.LookAt(focus);camera.Render();RenderTexture.active=iconRt;var icon=new Texture2D(256,256,TextureFormat.RGBA32,false);icon.ReadPixels(new Rect(0,0,256,256),0,0);icon.Apply();File.WriteAllBytes(Path.Combine(dir,"icon.png"),icon.EncodeToPNG());camera.targetTexture=null;RenderTexture.active=null;UnityEngine.Object.DestroyImmediate(icon);UnityEngine.Object.DestroyImmediate(iconRt);
 Log.Out("[JusticeQA] renders="+dir);Log.Out("[JusticeQA] feet="+r.FootL.position+" "+r.FootR.position);
 }catch(Exception e){fail++;Log.Error("[JusticeQA] "+e);}Log.Out("[MechaMotionQA] COMPLETE failures="+fail);}
}
