using System.Collections;
using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Diagnostics;using UnityEngine;using HarmonyLib;using PZAEC.Mecha;
// Identical native fixture for baseline and candidate; no player input/FPS claims.
public sealed class PolishNativeQA:IModApi {
 static World world;static Camera camera;static RenderTexture target;static Texture2D pixels;static string output;static List<string> report=new List<string>();static int failures;
 public void InitMod(Mod m){if(Environment.GetCommandLineArgs().Contains("-mechaMotionQA"))ModEvents.GameStartDone.RegisterHandler(Run);}
 static void Check(string name,bool pass){report.Add((pass?"PASS ":"FAIL ")+name);if(!pass)failures++;}
 static bool Pause(){return false;}
 static void Capture(EntityVehicle v,string name,Vector3 offset,bool fp=false){var r=Model.GetRig(v);var focus=name=="head-close"?r.Head.position:r.Mount.position+Vector3.up*1.65f;camera.transform.position=fp?Optics.CameraPosition(v,r,r.Mount.rotation,false):focus+offset;camera.transform.rotation=fp?r.Mount.rotation:Quaternion.LookRotation(focus-camera.transform.position);camera.fieldOfView=fp?80:38;
  var hidden=new List<Renderer>();if(fp)foreach(var p in r.FirstPersonHidden){if(!p.forceRenderingOff){p.forceRenderingOff=true;hidden.Add(p);}}
  // Synchronous captures need an explicit skin bake: Unity otherwise reuses
  // the previous render-frame skin while procedural attachments already moved.
  var finish=typeof(Justice).Assembly.GetType("PZAEC.Mecha.JusticeFinish");if(finish!=null)finish.GetMethod("SelectDetail").Invoke(null,new object[]{r.Justice,camera});
  var baked=new List<GameObject>();var original=new List<Renderer>();foreach(var part in r.Justice.Parts){if(!part.enabled||!part.gameObject.activeInHierarchy||part.forceRenderingOff)continue;var mesh=new Mesh();((SkinnedMeshRenderer)part).BakeMesh(mesh);var copy=new GameObject("Polish capture bake");copy.layer=30;copy.transform.SetPositionAndRotation(part.transform.position,part.transform.rotation);copy.transform.localScale=part.transform.lossyScale;copy.AddComponent<MeshFilter>().sharedMesh=mesh;copy.AddComponent<MeshRenderer>().sharedMaterial=part.sharedMaterial;baked.Add(copy);original.Add(part);part.forceRenderingOff=true;}
  camera.Render();RenderTexture.active=target;pixels.ReadPixels(new Rect(0,0,target.width,target.height),0,0);pixels.Apply();File.WriteAllBytes(Path.Combine(output,name+".png"),pixels.EncodeToPNG());foreach(var p in hidden)p.forceRenderingOff=false;foreach(var p in original)p.forceRenderingOff=false;foreach(var copy in baked){UnityEngine.Object.DestroyImmediate(copy.GetComponent<MeshFilter>().sharedMesh);UnityEngine.Object.DestroyImmediate(copy);}
 }
 static double P95(List<double> x){x.Sort();return x[(int)Math.Ceiling(x.Count*.95)-1];}
 static void Pose(EntityVehicle v,string pose,float t,float dt){var m=Locomotion.Get(v);var s=Samurai.Get(v);m.Grounded=pose=="ground"||pose=="walk"||pose=="combat"||pose=="board";m.SkimPhase=pose=="skim"?Skim.Phase.Cruise:pose=="brake"?Skim.Phase.Settling:Skim.Phase.Off;m.SkimAge=t;m.FlightMode=pose=="flight"||pose=="boost"||pose=="turn"?Flight.Phase.Cruise:pose=="landing"?Flight.Phase.Landing:pose=="fault"?Flight.Phase.PowerLost:Flight.Phase.Ground;m.WingBlend=Flight.AirPose(m)?1:0;m.Blend=Skim.Active(v)||Flight.Active(m)?1:0;m.Boost=pose=="boost"||pose=="skim";m.FlightHeight=pose=="landing"?.4f:5;m.VerticalInput=pose=="landing"?-1:0;m.LandingAt=-100;
  s.Swing=pose=="combat";s.Heavy=false;s.Combo=0;s.Started=Time.time-Mathf.Repeat(t,Samurai.NormalDuration);s.LaserCharge=pose=="rifle"?1:0;s.GuardHeld=s.Guarding=pose=="guard";s.GuardBlend=pose=="guard"?1:0;
  float speed=pose=="walk"?4:pose=="skim"?13.5f:pose=="boost"?20:pose=="flight"||pose=="turn"?12:0;var rb=v.vehicleRB;rb.position+=rb.rotation*Vector3.forward*(speed*dt);if(pose=="turn")rb.rotation*=Quaternion.Euler(0,30*dt,0);v.SetPosition(rb.position+Origin.position);Gait.Update(world,v,Model.GetRig(v),dt);
  if(pose=="board")Justice.Board(Model.GetRig(v),.75f);
 }
 static void Run(ref ModEvents.SGameStartDoneData data){bool automatic=Physics.autoSimulation;Physics.autoSimulation=false;try{
  world=GameManager.Instance.World;AccessTools.Field(typeof(Weapons),"currentWorld").SetValue(null,world);new Harmony("polish.native.qa").Patch(AccessTools.Method(typeof(Weapons),"Update"),prefix:new HarmonyMethod(typeof(PolishNativeQA),nameof(Pause)));
  output=Path.Combine(GameIO.GetSaveGameDir(),"polish-review");Directory.CreateDirectory(output);camera=new GameObject("Polish QA camera").AddComponent<Camera>();camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.065f,.08f,.105f);camera.cullingMask=1<<30;target=new RenderTexture(960,960,24);camera.targetTexture=target;camera.enabled=false;pixels=new Texture2D(960,960,TextureFormat.RGB24,false);
  var light=new GameObject("Polish key").AddComponent<Light>();light.type=LightType.Directional;light.intensity=1.65f;light.transform.rotation=Quaternion.Euler(35,-45,0);light.cullingMask=1<<30;RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Flat;var sh=new UnityEngine.Rendering.SphericalHarmonicsL2();sh.AddAmbientLight(new Color(.23f,.26f,.32f));RenderSettings.ambientProbe=sh;
  var fill=new GameObject("Polish rim").AddComponent<Light>();fill.type=LightType.Directional;fill.intensity=.65f;fill.color=new Color(.6f,.75f,1);fill.transform.rotation=Quaternion.Euler(15,135,0);fill.cullingMask=1<<30;
  var entities=new List<EntityVehicle>();for(int i=0;i<4;i++){var v=EntityFactory.CreateEntity(EntityClass.FromString(Rules.CompleteVehicle),new Vector3(i*5,400,0)+Origin.position) as EntityVehicle;world.SpawnEntityInWorld(v);v.vehicle.SetItemValue(ItemClass.GetItem(Rules.CompleteItem,false));for(var tr=v.vehicleRB.transform;tr!=null;tr=tr.parent)tr.gameObject.SetActive(true);v.vehicleRB.isKinematic=true;v.hasDriver=v.IsEngineRunning=true;v.vehicle.SetFuelLevel(100);var r=Model.GetRig(v);foreach(var tr in r.Mount.GetComponentsInChildren<Transform>(true))tr.gameObject.layer=30;entities.Add(v);if(i>0)r.Mount.gameObject.SetActive(false);}
  var first=entities[0];foreach(string pose in new[]{"ground","walk","skim","brake","flight","boost","turn","landing","fault","combat","guard","rifle","board"}){first.vehicleRB.position=new Vector3(0,400,0);first.vehicleRB.rotation=Quaternion.identity;first.SetPosition(first.vehicleRB.position+Origin.position);Gait.Forget(first);var r=Model.GetRig(first);r.ResetPose();for(int frame=0;frame<40;frame++)Pose(first,pose,frame/60f,1f/60);Capture(first,pose+"-front",new Vector3(5,1,9));Capture(first,pose+"-rear",new Vector3(-5,1,-9));Check("finite pose "+pose,Weapons.Finite(r.FootL.position.y)&&Weapons.Finite(r.Torso.rotation.x));}
  first.vehicleRB.position=new Vector3(0,400,0);first.vehicleRB.rotation=Quaternion.identity;first.SetPosition(first.vehicleRB.position+Origin.position);Pose(first,"ground",0,.02f);Capture(first,"head-close",new Vector3(.9f,.2f,1.8f));Capture(first,"first-person",Vector3.zero,true);light.intensity=.08f;fill.intensity=.12f;Capture(first,"night",new Vector3(5,1,9));light.intensity=1.65f;fill.intensity=.65f;
  var body=Model.GetRig(first).Justice.Parts[0].sharedMaterial;var originalNormal=body.GetTexture("_BumpMap");body.DisableKeyword("_NORMALMAP");Capture(first,"normal-off",new Vector3(1.4f,.7f,2.6f));body.EnableKeyword("_NORMALMAP");Capture(first,"normal-on",new Vector3(1.4f,.7f,2.6f));body.SetTexture("_BumpMap",originalNormal);
  var finish=typeof(Justice).Assembly.GetType("PZAEC.Mecha.JusticeFinish");if(finish!=null){var r=Model.GetRig(first);var j=r.Justice;var set=finish.GetMethod("SetDetail");var detail=AccessTools.Field(j.GetType(),"ForcedDetail");
   for(int level=0;level<3;level++){detail.SetValue(j,level);set.Invoke(null,new object[]{j,level});int triangles=0;foreach(var part in j.Parts)triangles+=((SkinnedMeshRenderer)part).sharedMesh.triangles.Length/3;Check("LOD budget "+level,triangles<=(level==0?60000:level==1?20000:9134));Capture(first,"lod-"+level,new Vector3(5,1,9));}detail.SetValue(j,2);set.Invoke(null,new object[]{j,2});Capture(first,"material-original-geometry",new Vector3(1.4f,.7f,2.6f));detail.SetValue(j,-1);
   foreach(int hz in new[]{30,60,120}){foreach(string mode in new[]{"walk","skim","brake","flight","boost","turn","landing","fault","rifle","ground"}){float peakAngle=0;for(int frame=0;frame<hz/2;frame++){var before=r.Torso.localRotation;float priorLean=(float)AccessTools.Field(j.GetType(),"AirLean").GetValue(j);Pose(first,mode,frame/(float)hz,1f/hz);if(frame>0)peakAngle=Mathf.Max(peakAngle,Quaternion.Angle(before,r.Torso.localRotation)*hz);float lean=(float)AccessTools.Field(j.GetType(),"AirLean").GetValue(j);if(Mathf.Abs(lean-priorLean)>40f/hz+.001f)throw new Exception("air lean rate exceeded");}Check("torso continuity "+hz+" "+mode+" deg/s="+peakAngle,peakAngle<=300);var jets=(Transform[])AccessTools.Field(j.GetType(),"Jets").GetValue(j);float thrust=(float)AccessTools.Field(j.GetType(),"Thrust").GetValue(j);bool powered=Locomotion.Powered(first);report.Add("THRUST "+hz+" "+mode+" "+thrust+" powered="+powered+" health="+first.vehicle.GetHealth());Check("finite "+hz+" "+mode,Weapons.Finite(r.Torso.rotation.x));if(mode=="fault")Check("power loss jets off "+hz,jets.All(x=>!x.gameObject.activeSelf));}}
   Pose(first,"boost",0,.2f);var js=(Transform[])AccessTools.Field(j.GetType(),"Jets").GetValue(j);foreach(var jet in js)report.Add("JET local="+jet.localPosition+" world-relative="+(jet.position-r.Mount.position)+" enabled="+jet.gameObject.activeSelf);
   first.IsEngineRunning=false;Pose(first,"boost",0,.02f);Check("engine loss immediately disables jets",js.All(x=>!x.gameObject.activeSelf));first.IsEngineRunning=true;
  }
  long calibrationBefore=GC.GetAllocatedBytesForCurrentThread();var calibration=new byte[4096];long allocationDelta=GC.GetAllocatedBytesForCurrentThread()-calibrationBefore;GC.KeepAlive(calibration);report.Add("ALLOCATION COUNTER CALIBRATION="+allocationDelta);
  first.vehicleRB.position=new Vector3(0,400,0);first.vehicleRB.rotation=Quaternion.identity;first.SetPosition(first.vehicleRB.position+Origin.position);Gait.Forget(first);for(int frame=0;frame<30;frame++)Pose(first,"ground",frame/60f,1f/60);var savedAlbedo=body.mainTexture;var savedColor=body.color;body.mainTexture=null;body.color=Color.white;body.DisableKeyword("_EMISSION");body.DisableKeyword("_METALLICGLOSSMAP");Capture(first,"white-normal",new Vector3(1.4f,.7f,2.6f));body.DisableKeyword("_NORMALMAP");Capture(first,"white-flat",new Vector3(1.4f,.7f,2.6f));body.mainTexture=savedAlbedo;body.color=savedColor;body.EnableKeyword("_EMISSION");body.EnableKeyword("_NORMALMAP");if(body.GetTexture("_MetallicGlossMap")!=null)body.EnableKeyword("_METALLICGLOSSMAP");
  var runner=new GameObject("Polish frame benchmark").AddComponent<PolishFrameRunner>();runner.StartCoroutine(runner.Guard(Benchmark(entities)));return;
 }catch(Exception e){Check("exception "+e,false);}finally{Physics.autoSimulation=automatic;}File.WriteAllLines(Path.Combine(output,"report.txt"),report);foreach(var line in report)Log.Out("[PolishQA] "+line);Log.Out("[PolishQA] output="+output);Log.Out("[MechaMotionQA] COMPLETE failures="+failures);}
 public static void Error(Exception e){Check("benchmark exception "+e,false);}
 public static void Complete(){File.WriteAllLines(Path.Combine(output,"report.txt"),report);foreach(var line in report)Log.Out("[PolishQA] "+line);Log.Out("[PolishQA] output="+output);Log.Out("[MechaMotionQA] COMPLETE failures="+failures);}
 static IEnumerator Benchmark(List<EntityVehicle> entities){bool savedAutomatic=Physics.autoSimulation;yield return null;Physics.autoSimulation=false;try{
  var rows=new List<string>{"count,run,samples,cpu_p95_ms,render_p95_ms,total_p95_ms,alloc_bytes_per_frame"};
  foreach(int count in new[]{1,4})for(int run=0;run<3;run++){
   for(int i=0;i<4;i++){var v=entities[i];Model.GetRig(v).Mount.gameObject.SetActive(i<count);v.vehicleRB.position=new Vector3(i*4,400,0);v.vehicleRB.rotation=Quaternion.identity;v.SetPosition(v.vehicleRB.position+Origin.position);Gait.Forget(v);}
   camera.fieldOfView=50;camera.transform.position=new Vector3((count-1)*2,402,count==1?-6:-23);camera.transform.LookAt(new Vector3((count-1)*2,401.5f,0));var cpu=new List<double>();var render=new List<double>();var total=new List<double>();long allocated=0;var timer=new Stopwatch();
   for(int frame=0;frame<180;frame++){yield return null;for(int i=0;i<count;i++){entities[i].hasDriver=entities[i].IsEngineRunning=true;entities[i].vehicleRB.isKinematic=true;entities[i].vehicleRB.position=new Vector3(i*4,400,0);entities[i].vehicleRB.rotation=Quaternion.identity;entities[i].SetPosition(entities[i].vehicleRB.position+Origin.position);Model.GetRig(entities[i]).Mount.localPosition=Vector3.zero;}long before=GC.GetAllocatedBytesForCurrentThread();timer.Restart();for(int i=0;i<count;i++)Pose(entities[i],"ground",frame/60f,1f/60);timer.Stop();double a=timer.Elapsed.TotalMilliseconds;long bytes=GC.GetAllocatedBytesForCurrentThread()-before;
    timer.Restart();camera.Render();RenderTexture.active=target;pixels.ReadPixels(new Rect(0,0,target.width,target.height),0,0,false);timer.Stop();double b=timer.Elapsed.TotalMilliseconds;if(frame>=60){cpu.Add(a);render.Add(b);total.Add(a+b);allocated+=bytes;}if(frame==120&&run==0){pixels.Apply();File.WriteAllBytes(Path.Combine(output,"performance-scene-"+count+".png"),pixels.EncodeToPNG());}}
   rows.Add(string.Format(System.Globalization.CultureInfo.InvariantCulture,"{0},{1},120,{2:F6},{3:F6},{4:F6},{5}",count,run,P95(cpu),P95(render),P95(total),-1));
  }File.WriteAllLines(Path.Combine(output,"performance.csv"),rows);
 }finally{Physics.autoSimulation=savedAutomatic;}
 }

}

public sealed class PolishFrameRunner:MonoBehaviour {
 public IEnumerator Guard(IEnumerator sequence){while(true){bool more=false;object next=null;try{more=sequence.MoveNext();if(more)next=sequence.Current;}catch(Exception e){PolishNativeQA.Error(e);}if(!more)break;yield return next;}PolishNativeQA.Complete();}
}
