using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using HarmonyLib;
using UnityEngine;
using PZAEC.Mecha;

// Recovery, braking and ordinary foot packets on the installed native engine.
// Synchronous PhysX fixtures; deliberately not advertised as two-client QA.
public sealed class MechaRoughSupportQA:IModApi
{
    static readonly List<string> lines=new List<string>();static int failures;static World world;
    public void InitMod(Mod m){if(Environment.GetCommandLineArgs().Contains("-mechaMotionQA"))ModEvents.GameStartDone.RegisterHandler(Run);}
    static void Check(string label,bool ok){string s=(ok?"PASS ":"FAIL ")+label;lines.Add(s);Log.Out("[MechaRoughQA] "+s);if(!ok)failures++;}
    static GameObject Floor(string name,Vector3 pos,Vector3 size){var g=new GameObject(name);g.layer=16;g.transform.position=pos;g.AddComponent<BoxCollider>().size=size;Physics.SyncTransforms();return g;}
    static EntityVehicle Spawn(string name){var v=EntityFactory.CreateEntity(EntityClass.FromString(name),new Vector3(0,400,0)+Origin.position) as EntityVehicle;world.SpawnEntityInWorld(v);for(var t=v.vehicleRB.transform;t!=null;t=t.parent)t.gameObject.SetActive(true);Reset(v);return v;}
    static void Reset(EntityVehicle v){Model.GetRig(v).ResetPose();Traversal.Forget(v);GroundNet.Forget(v);GroundSupport.Suspend(v);var s=GroundSupport.Get(v);var rb=v.vehicleRB;rb.isKinematic=false;rb.useGravity=true;rb.constraints=RigidbodyConstraints.None;rb.rotation=Quaternion.identity;rb.position=new Vector3(0,400+s.Shape.NeutralY+Rules.SoleClearance,0);rb.velocity=rb.angularVelocity=Vector3.zero;v.SetPosition(rb.position+Origin.position);Physics.SyncTransforms();GroundSupport.Observe(v);}
    static void Step(EntityVehicle v,float dt,Vector3 wanted){var s=GroundSupport.Observe(v);s.DesiredVelocity=wanted;var traversal=Traversal.Get(v);traversal.SearchAt=-100;float target=Traversal.LimitSpeed(v,s,wanted.z,dt);GroundSupport.Walking(s,dt,true);if(!GroundSupport.MotionClear(s,dt)){GroundSupport.StopHorizontal(s);target=0;}GroundSupport.Apply(s,dt);if(s.Grounded)Locomotion.ApplyDrive(v.vehicleRB,Vector3.forward,Mathf.Clamp(target,-s.DriveCap,s.DriveCap),0,false,s.Normal,dt);Physics.Simulate(dt);v.SetPosition(v.vehicleRB.position+Origin.position);Physics.SyncTransforms();Locomotion.Get(v).Grounded=s.Grounded;Gait.Update(world,v,Model.GetRig(v),dt);}
    static GroundWire Wire(EntityVehicle v,int actor,int seq){var s=GroundSupport.Get(v);var d=new GroundWire{Vehicle=v.entityId,Actor=actor,Sequence=seq,Flags=(byte)((s.Grounded?1:0)|(s.Feet[0].Planted?2:0)|(s.Feet[1].Planted?4:0)|(s.Recovering?8:0)|(s.Cautious?16:0)),Root=v.vehicleRB.position+Origin.position,Yaw=0};for(int i=0;i<2;i++){d.Feet[i]=s.Feet[i].Position;d.Normals[i]=s.Feet[i].Normal;}return d;}
    static GroundWire Copy(GroundWire d){using(var stream=new MemoryStream()){var w=new PooledBinaryWriter();w.SetBaseStream(stream);d.Write(w);w.Flush();Check("ground packet length "+stream.Length,stream.Length==GroundWire.Bytes);stream.Position=0;var r=new PooledBinaryReader();r.SetBaseStream(stream);var b=new GroundWire();b.Read(r);return b;}}
    static void Network(EntityVehicle v){var pilot=EntityFactory.CreateEntity(EntityClass.FromString("playerMale"),new Vector3(15,400,0)) as EntityPlayer;world.SpawnEntityInWorld(pilot);var seats=AccessTools.Field(typeof(Entity),"attachedEntities");var old=seats.GetValue(v);bool driver=v.hasDriver,engine=v.IsEngineRunning;
        try{seats.SetValue(v,new Entity[]{pilot});pilot.AttachedToEntity=v;v.hasDriver=v.IsEngineRunning=true;Reset(v);for(int i=0;i<25;i++)Step(v,.02f,Vector3.zero);var d=Copy(Wire(v,pilot.entityId,1));
            Check("server accepts real planted soles",GroundNet.ServerReceive(world,pilot.entityId,d));Check("duplicate foot frame rejected",!GroundNet.ServerReceive(world,pilot.entityId,d));var bad=Copy(d);bad.Sequence++;bad.Actor++;Check("foreign pilot rejected",!GroundNet.ServerReceive(world,bad.Actor,bad));bad=Copy(d);bad.Sequence++;bad.Feet[0].y=float.NaN;Check("nonfinite sole rejected",!bad.Valid());bad=Copy(d);bad.Flags=1;Check("ground flag without bearing sole rejected",!bad.Valid());bad=Copy(d);bad.Sequence++;bad.Feet[0]+=Vector3.up*.2f;Check("unsupported planted sole rejected",!GroundNet.ServerReceive(world,pilot.entityId,bad));
            var ground=GroundSupport.Get(v);var mode=Locomotion.Get(v);ground.Recovering=true;ground.Feet[0].Swing=true;mode.Toggle=true;Locomotion.RecoveryInputs(v,ground,mode);Check("takeoff waits during a committed recovery swing",!mode.Toggle&&ground.QueuedToggle);ground.Feet[0].Swing=false;Locomotion.RecoveryInputs(v,ground,mode);Check("failed recovery preparation can be cancelled by takeoff",mode.Toggle&&!ground.Initialized&&!ground.Recovering);mode.Toggle=false;Reset(v);for(int i=0;i<25;i++)Step(v,.02f,Vector3.zero);v.isEntityRemote=true;var velocity=v.vehicleRB.velocity;d.Sequence=100;Check("remote foot frame accepted",GroundNet.ClientReceive(world,d));Check("remote replay does not apply forces",v.vehicleRB.velocity==velocity);Check("late foot frame rejected",!GroundNet.ClientReceive(world,d));d.Sequence++;d.Flags=11;Check("single-foot recovery frame accepted",GroundNet.ClientReceive(world,d)&&GroundSupport.Get(v).Recovering);var m=Locomotion.Get(v);Check("recovery has no damaging landing authorization",m.AirSince<0&&!m.LandingEventExpected&&m.LandingPendingUntil<0);m.FlightMode=Flight.Phase.Takeoff;GroundNet.Tick(world);Check("takeoff clears stale ground recovery pose",!GroundNet.Fresh(v)&&!GroundSupport.Get(v).Recovering);d.Sequence++;Check("late ground frame cannot overwrite flight",!GroundNet.ClientReceive(world,d));m.FlightMode=Flight.Phase.Ground;d.Sequence++;GroundNet.ClientReceive(world,d);seats.SetValue(v,new Entity[0]);GroundNet.Tick(world);Check("pilot change clears recovery replay",!GroundNet.Fresh(v)&&!GroundSupport.Get(v).Recovering);
        }finally{foreach(var c in UnityEngine.Object.FindObjectsOfType<Collider>())if(GroundSupport.Own(v,c))c.enabled=false;pilot.transform.gameObject.SetActive(false);v.isEntityRemote=false;v.hasDriver=driver;v.IsEngineRunning=engine;seats.SetValue(v,old);pilot.AttachedToEntity=null;world.RemoveEntity(pilot.entityId,EnumRemoveEntityReason.Despawned);GroundNet.Forget(v);}}
    static void Recovery(EntityVehicle v){var s=GroundSupport.Get(v);var home=s.Shape.Home;var left=Floor("temporary left sole",new Vector3(home[0].x,399.5f,home[0].z),new Vector3(.80f,1,.80f));var right=Floor("permanent right sole",new Vector3(home[1].x,399.5f,home[1].z),new Vector3(.85f,1,2));var next=Floor("nearby recovery sole",new Vector3(home[0].x,399.5f,home[0].z+.43f),new Vector3(.85f,1,.80f));GameObject lower=null;
        try{Reset(v);for(int i=0;i<40;i++)Step(v,.02f,Vector3.zero);Check("double support before collapse",s.Feet.All(f=>f.Planted));UnityEngine.Object.DestroyImmediate(left);Physics.SyncTransforms();bool lost=false,restored=false;float slip=0;
            for(int i=0;i<200;i++){Step(v,.02f,Vector3.zero);lost|=s.Recovering;if(lost&&s.Feet.All(f=>f.Planted)){restored=true;break;}var rig=Model.GetRig(v);if(s.Feet[1].Planted)slip=Mathf.Max(slip,Vector3.Distance(rig.FootR.position+Origin.position,s.Feet[1].Position));}
            Check("one bearing foot can recover to a nearby full sole "+GroundSupport.Diagnostics(v),lost&&restored&&s.Grounded);Check("bearing foot remains fixed during recovery "+slip,slip<=.05f);lower=Floor("real landing below collapse",new Vector3(0,396.5f,0),new Vector3(30,1,30));UnityEngine.Object.DestroyImmediate(right);UnityEngine.Object.DestroyImmediate(next);Physics.SyncTransforms();float y=v.vehicleRB.position.y;for(int i=0;i<30;i++)Step(v,.02f,Vector3.zero);Check("both destroyed pads fall under gravity",!s.Grounded&&v.vehicleRB.position.y<y-1);for(int i=0;i<120;i++)Step(v,.02f,Vector3.zero);Check("real landing rebuilds support without stale recovery "+GroundSupport.Diagnostics(v),s.Grounded&&s.Feet.All(f=>f.Planted)&&!s.Recovering);
        }finally{if(left!=null)UnityEngine.Object.DestroyImmediate(left);if(right!=null)UnityEngine.Object.DestroyImmediate(right);if(next!=null)UnityEngine.Object.DestroyImmediate(next);if(lower!=null)UnityEngine.Object.DestroyImmediate(lower);}}
    static void FlatBoost(EntityVehicle v){var floor=Floor("long flat boost lane",new Vector3(0,399.5f,40),new Vector3(30,1,120));try{Reset(v);float peak=0;bool lost=false;for(int i=0;i<500;i++){Step(v,.02f,Vector3.forward*13.5f);peak=Mathf.Max(peak,v.vehicleRB.velocity.z);lost|=!GroundSupport.Get(v).Grounded;}Check("flat boost retains speed and support peak="+peak,peak>=12&&!lost);Network(v);}finally{UnityEngine.Object.DestroyImmediate(floor);}}
    static void Run(ref ModEvents.SGameStartDoneData data){if(GamePrefs.GetString(EnumGamePrefs.GameName)!="MechaQA_Isolated")return;world=GameManager.Instance.World;bool auto=Physics.autoSimulation;Physics.autoSimulation=false;
        try{foreach(string name in new[]{Rules.VehicleName,Rules.CompleteVehicle}){var v=Spawn(name);try{Recovery(v);FlatBoost(v);}finally{foreach(var c in UnityEngine.Object.FindObjectsOfType<Collider>())if(GroundSupport.Own(v,c))c.enabled=false;v.vehicleRB.gameObject.SetActive(false);v.transform.gameObject.SetActive(false);world.RemoveEntity(v.entityId,EnumRemoveEntityReason.Despawned);GroundSupport.Forget(v);}}}catch(Exception e){Check("exception "+e,false);}finally{Physics.autoSimulation=auto;}
        lines.Add("LIMIT: native same-process protocol and PhysX tests, not two-client networking.");var path=Path.Combine(GameIO.GetSaveGameDir(),"mecha-rough-support-qa.txt");File.WriteAllLines(path,lines);Log.Out("[MechaMotionQA] COMPLETE failures="+failures+" report="+path);}
}
