using System;using System.IO;using Newtonsoft.Json;using UnityEngine;using UnityEngine.Rendering;
namespace PZAEC.Mecha {
 public sealed class JusticeDetailView:MonoBehaviour {
  public JusticeRig Owner;
  void OnWillRenderObject(){if(Owner!=null)JusticeFinish.SelectDetail(Owner,Camera.current);}
 }
 public static class JusticeFinish {
  public sealed class Part{public int sourcePart,lod,offset,vertices,indices;}
  public sealed class Jet{public int bone;public float[] position,direction;}
  public sealed class Document{public int version,vertexStride;public string sourceSha256,geometry,albedo,normal,material,emission;public Part[] parts;public Jet[] jets;public float[] lodHeights;}
  static Document doc;static Mesh[][] meshes;static Material thrustMaterial;static Mesh cone;
  static string PathOf(string name){return Path.Combine(Model.Path,"Justice",name);}
  static void Load(string name){if(doc!=null||string.IsNullOrEmpty(name))return;doc=JsonConvert.DeserializeObject<Document>(File.ReadAllText(PathOf(name)));if(doc.version!=2||doc.vertexStride!=80||doc.sourceSha256!=JsonConvert.DeserializeObject<Justice.Document>(File.ReadAllText(PathOf("justice.json"))).sourceSha256)throw new InvalidDataException("Justice polish format");}
  static Texture2D Texture(string file,bool linear){var t=new Texture2D(2,2,TextureFormat.RGBA32,true,linear){name=file,filterMode=FilterMode.Trilinear,anisoLevel=8};ImageConversion.LoadImage(t,File.ReadAllBytes(PathOf(file)));t.Apply(true,true);return t;}
  public static void Materials(Material[] materials,string name){Load(name);if(doc==null)return;var body=materials[0];UnityEngine.Object.Destroy(body.mainTexture);UnityEngine.Object.Destroy(body.GetTexture("_BumpMap"));UnityEngine.Object.Destroy(body.GetTexture("_EmissionMap"));body.mainTexture=Texture(doc.albedo,false);body.SetTexture("_BumpMap",Texture(doc.normal,true));body.SetFloat("_BumpScale",.7f);body.EnableKeyword("_NORMALMAP");var mask=Texture(doc.material,true);body.SetTexture("_MetallicGlossMap",mask);body.SetFloat("_GlossMapScale",1);body.EnableKeyword("_METALLICGLOSSMAP");body.SetTexture("_OcclusionMap",mask);body.SetFloat("_OcclusionStrength",.8f);body.SetTexture("_EmissionMap",Texture(doc.emission,false));body.SetColor("_EmissionColor",Color.white*1.4f);materials[1].SetColor("_EmissionColor",new Color(1.8f,.35f,1.3f));}
  public static void Build(JusticeRig rig,string name,int layer){Load(name);if(doc==null)return;
   if(meshes==null){meshes=new Mesh[3][];for(int lod=0;lod<3;lod++)meshes[lod]=new Mesh[rig.Parts.Length];for(int i=0;i<rig.Parts.Length;i++)meshes[2][i]=((SkinnedMeshRenderer)rig.Parts[i]).sharedMesh;
    using(var reader=new BinaryReader(File.OpenRead(PathOf(doc.geometry))))foreach(var p in doc.parts){if(p.sourcePart<0||p.sourcePart>=rig.Parts.Length||p.lod<0||p.lod>1||p.vertices<=0||p.indices%3!=0||p.offset<0||(long)p.offset+p.vertices*80L+p.indices*4L>reader.BaseStream.Length)throw new InvalidDataException("Justice polish mesh bounds");reader.BaseStream.Position=p.offset;var v=new Vector3[p.vertices];var n=new Vector3[p.vertices];var uv=new Vector2[p.vertices];var w=new BoneWeight[p.vertices];var t=new Vector4[p.vertices];var ix=new int[p.indices];
     for(int k=0;k<v.Length;k++){v[k]=new Vector3(reader.ReadSingle(),reader.ReadSingle(),reader.ReadSingle());n[k]=new Vector3(reader.ReadSingle(),reader.ReadSingle(),reader.ReadSingle());uv[k]=new Vector2(reader.ReadSingle(),1-reader.ReadSingle());w[k]=new BoneWeight{boneIndex0=reader.ReadInt32(),boneIndex1=reader.ReadInt32(),boneIndex2=reader.ReadInt32(),boneIndex3=reader.ReadInt32(),weight0=reader.ReadSingle(),weight1=reader.ReadSingle(),weight2=reader.ReadSingle(),weight3=reader.ReadSingle()};t[k]=new Vector4(reader.ReadSingle(),reader.ReadSingle(),reader.ReadSingle(),reader.ReadSingle());}
     for(int k=0;k<ix.Length;k++){ix[k]=reader.ReadInt32();if(ix[k]<0||ix[k]>=v.Length)throw new InvalidDataException("Justice polish index");}
     var mesh=new Mesh{name="Justice polished LOD"+p.lod+" "+rig.Roles[p.sourcePart],indexFormat=IndexFormat.UInt32};mesh.vertices=v;mesh.normals=n;mesh.uv=uv;mesh.boneWeights=w;mesh.bindposes=meshes[2][p.sourcePart].bindposes;mesh.triangles=ix;mesh.tangents=t;mesh.RecalculateBounds();meshes[p.lod][p.sourcePart]=mesh;
    }
   }
   for(int i=0;i<rig.Parts.Length;i++){if(meshes[0][i]==null||meshes[1][i]==null)throw new InvalidDataException("Incomplete Justice LOD");if(rig.Roles[i]=="Torso"){var callback=rig.Parts[i].gameObject.AddComponent<JusticeDetailView>();callback.Owner=rig;}rig.Parts[i].shadowCastingMode=ShadowCastingMode.On;rig.Parts[i].receiveShadows=true;}
   rig.BlendRot=new Quaternion[rig.Bones.Length];rig.BlendPos=new Vector3[rig.Bones.Length];for(int i=0;i<rig.Bones.Length;i++){rig.BlendRot[i]=rig.Bones[i].localRotation;rig.BlendPos[i]=rig.Bones[i].localPosition;}SetDetail(rig,0);
   if(cone==null){cone=new Mesh{name="Justice pooled thruster"};var v=new Vector3[24];var ix=new int[144];for(int i=0;i<12;i++){float a=i*Mathf.PI/6;v[i]=new Vector3(Mathf.Cos(a),Mathf.Sin(a),0);v[12+i]=new Vector3(Mathf.Cos(a)*.10f,Mathf.Sin(a)*.10f,1);}int at=0;for(int i=0;i<12;i++){int k=(i+1)%12;foreach(int j in new[]{i,k,12+k,i,12+k,12+i,k,i,12+k,12+k,i,12+i})ix[at++]=j;}var colors=new Color[24];for(int i=0;i<12;i++){colors[i]=new Color(1,1,1,.7f);colors[12+i]=new Color(1,1,1,0);}cone.vertices=v;cone.colors=colors;cone.triangles=ix;cone.RecalculateNormals();cone.RecalculateBounds();var shader=Shader.Find("Sprites/Default")??Shader.Find("Unlit/Color");thrustMaterial=new Material(shader){name="Justice thrust",color=new Color(.22f,.65f,1,.8f)};}
   rig.Jets=new Transform[doc.jets.Length];for(int i=0;i<rig.Jets.Length;i++){var jet=doc.jets[i];var go=new GameObject("JusticeThruster"+i);go.layer=layer;go.transform.SetParent(rig.Bones[jet.bone],false);go.transform.localPosition=new Vector3(jet.position[0],jet.position[1],jet.position[2]);go.transform.localRotation=Quaternion.LookRotation(new Vector3(jet.direction[0],jet.direction[1],jet.direction[2]));go.AddComponent<MeshFilter>().sharedMesh=cone;var renderer=go.AddComponent<MeshRenderer>();renderer.sharedMaterial=thrustMaterial;renderer.shadowCastingMode=ShadowCastingMode.Off;renderer.receiveShadows=false;go.AddComponent<MechaRenderPart>().Role="Backpack";rig.Jets[i]=go.transform;go.SetActive(false);}
  }
  public static void SetDetail(JusticeRig rig,int level){if(rig.Ultimate)return;if(doc==null||meshes==null)return;level=Mathf.Clamp(level,0,2);if(rig.DetailLevel==level)return;for(int i=0;i<rig.Parts.Length;i++)((SkinnedMeshRenderer)rig.Parts[i]).sharedMesh=meshes[level][i];rig.DetailLevel=level;}
  public static void SelectDetail(JusticeRig rig,Camera camera){if(doc==null||camera==null)return;if(rig.ForcedDetail>=0){SetDetail(rig,rig.ForcedDetail);return;}if(rig.Vehicle!=null&&Optics.Active(rig.Vehicle)&&!Optics.ThirdPerson){SetDetail(rig,0);return;}int cameraId=camera.GetInstanceID();if(rig.DetailFrame==Time.frameCount&&rig.DetailCamera==cameraId&&rig.DetailCameraPosition==camera.transform.position&&rig.DetailPosition==rig.transform.position&&rig.DetailFov==camera.fieldOfView)return;rig.DetailFrame=Time.frameCount;rig.DetailCamera=cameraId;rig.DetailCameraPosition=camera.transform.position;rig.DetailPosition=rig.transform.position;rig.DetailFov=camera.fieldOfView;float distance=Vector3.Distance(camera.transform.position,rig.transform.position+Vector3.up*1.6f);float height=camera.orthographic?3.2f/(2*camera.orthographicSize):3.2f/(2*Mathf.Max(distance,.1f)*Mathf.Tan(camera.fieldOfView*Mathf.Deg2Rad*.5f));int level=height>=doc.lodHeights[0]?0:height>=doc.lodHeights[1]?1:2;SetDetail(rig,level);}
  // Motion is driven by the actual support feet, not a second free-running clock.
  public static void Weight(EntityVehicle v,Model.Rig r,float dt){JusticeMotion.Body(v,r,dt);}
  // Blend upper-body presentation before the final foot solver. Active attack
  // arm/weapon transforms stay authoritative so hit timing and blade paths agree.
  public static void Blend(EntityVehicle v,Model.Rig r,float dt){var j=r.Justice;if(j.BlendRot==null)return;var m=Locomotion.Get(v);var c=Samurai.Get(v);int kind=c.Swing||c.Charging?5:c.LaserCharge>0||c.BeamSpent?6:c.Guarding?7:Flight.AirPose(m)?3:Skim.Active(v)?2:j.WalkBlend>.1f?1:0;
   if(j.PoseKind!=kind){j.PoseKind=kind;j.PoseBlend=0;}j.PoseBlend=Mathf.MoveTowards(j.PoseBlend,1,dt/.16f);float a=Mathf.SmoothStep(0,1,j.PoseBlend);
   for(int i=0;i<j.Bones.Length;i++){var bone=j.Bones[i];bool leg=bone==r.HipL||bone==r.HipR||bone==r.KneeL||bone==r.KneeR||bone==r.AnkleL||bone==r.AnkleR;bool authoritative=c.Swing||c.Charging;
    if(!leg&&!authoritative&&!(bone==r.Torso&&!j.Ultimate&&Traversal.Active(v))){bone.localRotation=Quaternion.Slerp(j.BlendRot[i],bone.localRotation,a);if(bone==r.Torso)bone.localPosition=Vector3.Lerp(j.BlendPos[i],bone.localPosition,a);}
    j.BlendRot[i]=bone.localRotation;j.BlendPos[i]=bone.localPosition;
   }
  }
  public static void Thrust(EntityVehicle v,JusticeRig rig,float dt){if(rig.Jets==null)return;if(Optics.Active(v)&&!Optics.ThirdPerson)SetDetail(rig,0);var m=Locomotion.Get(v);float target=!Locomotion.Powered(v)||m.FlightMode==Flight.Phase.PowerLost?0:Flight.Active(m)?(m.Boost?1:m.VerticalInput>0?.8f:.5f):Skim.Active(v)?(m.SkimPhase==Skim.Phase.Settling?.25f:.7f):0;rig.Thrust=target==0?0:Mathf.MoveTowards(rig.Thrust,target,dt*5);for(int i=0;i<rig.Jets.Length;i++){var jet=rig.Jets[i];jet.gameObject.SetActive(rig.Thrust>.01f);jet.localScale=new Vector3(.055f,.055f,.10f+rig.Thrust*.35f);}}
 }
}
