using System;using System.IO;using Newtonsoft.Json;using UnityEngine;using UnityEngine.Rendering;
namespace PZAEC.Mecha {
 // Per-chassis immutable data prevents Justice and Nu instances exchanging skeletons or clips.
 public static class Nu {
  static Justice.Document doc;static byte[] bytes;static Material[] materials;static Material thrust;
  public static Justice.Document Document{get{Load();return doc;}}public static byte[] Bytes{get{Load();return bytes;}}
  static string FileAt(string file){return Path.Combine(Model.Path,"Nu",file);}
  static void Load(){if(doc!=null)return;var data=JsonConvert.DeserializeObject<Justice.Document>(File.ReadAllText(FileAt("nu.json")));using(var sha=System.Security.Cryptography.SHA256.Create())using(var stream=File.OpenRead(FileAt("nu.glb")))if(BitConverter.ToString(sha.ComputeHash(stream)).Replace("-","").ToLowerInvariant()!=data.sourceSha256)throw new InvalidDataException("Nu source hash mismatch");bytes=File.ReadAllBytes(FileAt("nu.bin"));doc=data;}
  static Texture2D Texture(string file,bool linear){if(string.IsNullOrEmpty(file))return null;var t=new Texture2D(2,2,TextureFormat.RGBA32,true,linear){name="Nu "+file,filterMode=FilterMode.Trilinear,anisoLevel=4};if(!ImageConversion.LoadImage(t,File.ReadAllBytes(FileAt(file)),true))throw new InvalidDataException(file);return t;}
  public static void Build(Transform mount,int layer){Load();if(materials==null){materials=new Material[doc.materials.Length];for(int i=0;i<materials.Length;i++){var s=doc.materials[i];var m=new Material(Shader.Find("Standard")){name="Nu "+s.name,color=new Color(s.color[0],s.color[1],s.color[2],s.color[3])};m.mainTexture=Texture(s.albedo,false);m.SetFloat("_Metallic",s.metallic);m.SetFloat("_Glossiness",1-s.roughness);if(!string.IsNullOrEmpty(s.normal)){m.SetTexture("_BumpMap",Texture(s.normal,true));m.EnableKeyword("_NORMALMAP");}if(!string.IsNullOrEmpty(s.mask)){m.SetTexture("_MetallicGlossMap",Texture(s.mask,true));m.SetFloat("_GlossMapScale",1);m.EnableKeyword("_METALLICGLOSSMAP");}if(s.emission!=null&&s.emission.Length==3){m.SetColor("_EmissionColor",new Color(s.emission[0],s.emission[1],s.emission[2]));m.EnableKeyword("_EMISSION");}materials[i]=m;}}Justice.BuildSkin(mount,layer,doc,bytes,materials,true);}
  public static void Finish(JusticeRig rig,int layer){rig.BlendRot=new Quaternion[rig.Bones.Length];rig.BlendPos=new Vector3[rig.Bones.Length];for(int i=0;i<rig.Bones.Length;i++){rig.BlendRot[i]=rig.BaseRot[i];rig.BlendPos[i]=rig.BasePos[i];}Transform pack=null;for(int i=0;i<doc.bones.Length;i++)if(doc.bones[i].sourceNode==65)pack=rig.Bones[i];
   if(thrust==null)thrust=new Material(Shader.Find("Sprites/Default")){name="Nu blue thrust",color=new Color(.2f,.55f,1,.65f)};
   rig.Jets=new Transform[2];for(int side=0;side<2;side++){var go=new GameObject("NuThruster"+side);go.layer=layer;go.transform.SetParent(pack,false);go.transform.localPosition=new Vector3(side==0?-.16f:.16f,-.2f,-.08f);go.transform.localRotation=Quaternion.Euler(90,0,0);var mesh=new Mesh();var v=new Vector3[18];var ix=new int[96];int at=0;for(int k=0;k<8;k++){float a=k*Mathf.PI/4;v[k]=new Vector3(Mathf.Cos(a),Mathf.Sin(a),0);v[k+8]=new Vector3(Mathf.Cos(a)*.08f,Mathf.Sin(a)*.08f,1);}for(int k=0;k<8;k++){int q=(k+1)%8;foreach(int j in new[]{k,q,q+8,k,q+8,k+8,q,k,q+8,q+8,k,k+8})ix[at++]=j;}mesh.vertices=v;mesh.triangles=ix;mesh.RecalculateNormals();mesh.RecalculateBounds();go.AddComponent<MeshFilter>().sharedMesh=mesh;go.AddComponent<MeshRenderer>().sharedMaterial=thrust;go.AddComponent<MechaRenderPart>().Role="Backpack";rig.Jets[side]=go.transform;go.SetActive(false);}
  }
 }
}
