from pathlib import Path
import xml.etree.ElementTree as E,copy,csv
root=Path(__file__).resolve().parents[2];out=root/'95-PhoenixBoss';native=E.parse(root.parent/'Data/Config/items.xml')
def prop(e,k,v):E.SubElement(e,'property',name=k,value=str(v))
def write(e,p):E.indent(e,space='  ');E.ElementTree(e).write(p,encoding='utf-8',xml_declaration=True)
items=E.Element('configs');ia=E.SubElement(items,'append',xpath='/items');entities=E.Element('configs');ea=E.SubElement(entities,'append',xpath='/entity_classes')
health=[80000000,150000000,260000000,450666667];rows=[['Key','File','Type','UsedInMainMenu','NoTranslate','english','schinese']]
for tier in range(16,20):
 i=tier-16;hand='yfPhoenixHandT'+str(tier);ammo='yfPhoenixFireballT'+str(tier);name='yfPhoenixBossT'+str(tier)
 h=copy.deepcopy(native.find("item[@name='meleeHandAnimalZombieVultureRadiated']"));h.set('name',hand);ia.append(h)
 a=h.find("property[@class='Action0']");a.find("property[@name='DamageEntity']").set('value',str(0));a.find("property[@name='DamageBlock']").set('value',str(0))
 a=h.find("property[@class='Action1']");a.find("property[@name='Magazine_items']").set('value',ammo);a.find("property[@name='Particles_muzzle_fire']").set('value','');a.find("property[@name='Delay']").set('value','1.2');prop(a,'WarningMax',0);prop(a,'WarningDelay',0)
 for eg in list(h.findall('effect_group')):h.remove(eg)
 eg=E.SubElement(h,'effect_group',name=hand,tiered='false')
 for key,val in [('ModSlots',0),('MagazineSize',1),('BurstRoundCount',2),('SpreadDegreesVertical',2),('SpreadDegreesHorizontal',2),('MaxRange',60),('DamageFalloffRange',60)]:E.SubElement(eg,'passive_effect',name=key,operation='base_set',value=str(val))
 p=E.SubElement(ia,'item',name=ammo);prop(p,'Meshfile','#@modfolder:Resources/phoenix-fire.unity3d?Assets/Phoenix/PhoenixFireball.prefab');prop(p,'Material','Morganic');prop(p,'CreativeMode','None');prop(p,'CustomIcon','ammoRocketHE')
 a=E.SubElement(p,'property',{'class':'Action1'})
 for k,v in dict(Class='Projectile',DamageEntity=600+200*i,DamageBlock=3000+1000*i,Velocity=24,FlyTime=5,LifeTime=6,Gravity=0,CollisionRadius=.28,Buff='buffBurningFlamingArrow').items():prop(a,k,v)
 explosion=E.SubElement(a,'property',{'class':'Explosion'})
 for k,v in dict(BlockDamage=6000+2000*i,EntityDamage=1200+400*i,ParticleIndex=10,Duration=30,Buff="buffBurningMolotov",RadiusBlocks=4,RadiusEntities=5).items():prop(explosion,k,v)
 eg=E.SubElement(p,'effect_group',name=ammo,tiered='false');E.SubElement(eg,'passive_effect',name='BuffProcChance',operation='base_set',value='1',tags='buffBurningFlamingArrow')
 e=E.SubElement(ea,'entity_class',name=name,extends='animalZombieVulture')
 for k,v in dict(Class='YFPhoenix.EntityPhoenixBoss, YF.Phoenix',UserSpawnType='Menu',Tags='entity,animal,zombie,hostile,vulture,boss,yfPhoenix',SizeScale=2,HandItem=hand,ExperienceGain=200000+100000*i,LootDropProb=1,LootDropEntityClass='EntityLootContainerBoss',SightRange=90,MoveSpeed=1.3,MoveSpeedAggro='2.1, 2.1',Mass=300).items():prop(e,k,v)
 eg=E.SubElement(e,'effect_group',name='Phoenix finale health');E.SubElement(eg,'passive_effect',name='HealthMax',operation='base_set',value=str(health[i]));E.SubElement(eg,'passive_effect',name='HealthMax',operation='perc_set',value='1');rows.append([name,'entityclasses','Entity','','false','Ashen Phoenix T'+str(tier),'焚天凤凰 · T'+str(tier)])
write(items,out/'Config/items.xml');write(entities,out/'Config/entityclasses.xml')
with (out/'Config/Localization.csv').open('w',encoding='utf-8-sig',newline='') as f:csv.writer(f).writerows(rows)
info=E.Element('xml')
for k,v in dict(Name='YFPhoenixBoss',DisplayName='血月终章：焚天凤凰',Description='T16-T19血月结束后的飞行火焰Boss。',Author='yf',Version='0.1.1',ServerSideOnly='false',SkipWithAntiCheat='true').items():E.SubElement(info,k,value=v)
write(info,out/'ModInfo.xml')
