using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using HarmonyLib;
using YFPhoenix;
public sealed class PhoenixGameQA:IModApi {
 const string Folder="E:/soft/7DTD-Modding/PhoenixBoss";static World world;static EntityPlayer player,player2;static int phase;static float deadline;static List<string> report=new List<string>();static EntityPhoenixBoss flyingBoss;static Vector3 initialPosition;static int shots,aiTicks,attempts;static float nextManualTick;static List<float> shotTimes=new List<float>();static List<float> ringTimes=new List<float>();static HashSet<int> targets=new HashSet<int>();static HashSet<int> ringAngles=new HashSet<int>();
 public void InitMod(Mod mod){if(!Environment.GetCommandLineArgs().Contains("-yfPhoenixQA"))return;ModEvents.GameStartDone.RegisterHandler(Ready);ModEvents.GameUpdate.RegisterHandler(Update);}
 public static void Attempt(ItemActionData __0,bool __1){if(!__1&&__0.invData.holdingEntity is EntityPhoenixBoss){attempts++;if(attempts%80==0){var a=(ItemActionVomit.ItemActionDataVomit)__0;Log.Out("[PhoenixQA] ATTEMPT started="+a.bAttackStarted+" count="+a.numVomits+" burstStarted="+a.burstShotStarted+" burstFinished="+a.burstShotFinished+" last="+a.m_LastShotTime+" delay="+a.Delay+" now="+Time.time);}}}
 public static void AITick(EntityVulture __instance){if(__instance is EntityPhoenixBoss)aiTicks++;}
 public static void Shot(ProjectileMoveScript __instance){if(ReferenceEquals(__instance.firingEntity,flyingBoss)&&flyingBoss!=null){shots++;var boss=(EntityPhoenixBoss)__instance.firingEntity;bool ring=(bool)AccessTools.Field(typeof(EntityPhoenixBoss),"radial").GetValue(boss);if(ring){if(ringTimes.Count==0||Time.time-ringTimes.Last()>1){ringTimes.Add(Time.time);ringAngles.Clear();}var d=boss.GetLookVector();ringAngles.Add(Mathf.RoundToInt(Mathf.Atan2(d.z,d.x)*100));}else{shotTimes.Add(Time.time);var target=(EntityPlayer)AccessTools.Field(typeof(EntityPhoenixBoss),"fireTarget").GetValue(boss);if(target!=null)targets.Add(target.entityId);}Log.Out("[PhoenixQA] Native fireball launched "+shots);}}
 public static bool Stage(EntityPlayer __instance,ref int __result){if(!ReferenceEquals(__instance,player))return true;__result=180000;return false;}
 public static bool Identity(EntityPlayer p,ref string __result){if(!ReferenceEquals(p,player))return true;__result="phoenix-qa-only";return false;}
 public static bool Bot(EntityPlayer __instance)=>!ReferenceEquals(__instance,player)&&!ReferenceEquals(__instance,player2);
 static void Check(bool ok,string msg){if(!ok)throw new Exception(msg);report.Add("PASS "+msg);}
 static void Ready(ref ModEvents.SGameStartDoneData data){if(!GamePrefs.GetString(EnumGamePrefs.GameName).StartsWith("PhoenixQA_Isolated",StringComparison.Ordinal))return;world=GameManager.Instance.World;GameManager.Instance.AddChunkObserver(new Vector3(8,80,8),false,4,4);phase=1;deadline=Time.realtimeSinceStartup+180;}
 static void CheckHitboxes(){
  var colliders=flyingBoss.GetComponentsInChildren<CapsuleCollider>().Where(c=>c.name.StartsWith("PhoenixHit_")).ToArray();
  Check(colliders.Length==8,"server creates body, head, wing and tail hitboxes");Physics.SyncTransforms();
  foreach(var c in colliders){RaycastHit hit;Check(c.Raycast(new Ray(c.bounds.center+Vector3.up*10,Vector3.down),out hit,20),"projectile ray intersects "+c.name);Check(GameUtils.GetHitRootEntity(c.tag,c.transform)==flyingBoss,"hitbox resolves to Phoenix entity: "+c.name);Check(Voxel.Raycast(world,new Ray(c.bounds.center+Vector3.up*10,Vector3.down),20,-538751005,8,0)&&GameUtils.GetHitRootEntity(Voxel.voxelRayHitInfo.tag,Voxel.voxelRayHitInfo.transform)==flyingBoss,"native weapon ray hits Phoenix at "+c.name);}
  var model=flyingBoss.GetComponentsInChildren<Transform>().First(t=>t.name.StartsWith("PhoenixBoss(Clone)"));
  var mesh=model.GetComponentInChildren<SkinnedMeshRenderer>();var baked=new Mesh();mesh.BakeMesh(baked);var bounds=new Bounds(mesh.transform.TransformPoint(baked.vertices[0]),Vector3.zero);foreach(var v in baked.vertices)bounds.Encapsulate(mesh.transform.TransformPoint(v));UnityEngine.Object.Destroy(baked);
  report.Add("INFO visible world bounds="+bounds.size+" model scale="+model.lossyScale);
  Check(bounds.size.x>1&&Mathf.Max(bounds.size.x,Mathf.Max(bounds.size.y,bounds.size.z))<15,"visible Phoenix size is bounded independently of native carrier scale");
  int health=flyingBoss.Health;flyingBoss.DamageEntity(new DamageSourceEntity(EnumDamageSource.External,EnumDamageTypes.Piercing,player.entityId),10000,false,1f);Check(flyingBoss.Health<health,"native player damage reduces Phoenix health");
 }
 static void Tick(){AccessTools.Field(typeof(PhoenixEncounter),"next").SetValue(null,0f);var d=default(ModEvents.SGameUpdateData);PhoenixEncounter.Update(ref d);}
 static void Update(ref ModEvents.SGameUpdateData data){if(phase==0)return;
  if(phase==2){if(Time.realtimeSinceStartup<deadline){if(Time.realtimeSinceStartup>=nextManualTick){nextManualTick=Time.realtimeSinceStartup+.05f;flyingBoss.OnUpdateEntity();}return;}var ad=flyingBoss.inventory.holdingItemData.actionData[1] as ItemActionVomit.ItemActionDataVomit;var ar=flyingBoss.inventory.holdingItem.Actions[1] as ItemActionRanged;report.Add("INFO attempts="+attempts+" valid="+flyingBoss.IsAttackValid()+" maxAmmo="+ar.GetMaxAmmoCount(ad)+" range="+ar.GetRange(ad)+" started="+ad.bAttackStarted+" active="+ad.isActive+" warning="+ad.warningTime+" time="+Time.time+" num="+ad.numVomits+" meta="+ad.invData.itemValue.Meta+" lastShot="+ad.m_LastShotTime);report.Add("INFO native ticks="+aiTicks+" pos="+flyingBoss.position+" initial="+initialPosition+" motion="+flyingBoss.motion+" sleeping="+flyingBoss.IsSleeping+" passive="+flyingBoss.IsSleeperPassive+" gameState="+GameStats.GetInt(EnumGameStats.GameState));phase=0;try{Check(flyingBoss!=null&&(flyingBoss.position-initialPosition).sqrMagnitude>4,"native flying AI moves phoenix through air");Check(shots>=6,"native flying AI fires at least six projectiles");report.Add("INFO shot times="+string.Join(",",shotTimes));Check(shotTimes.Count>=6&&shotTimes.Last()-shotTimes.First()>=24,"ranged attacks continue across multiple volleys for at least 24 seconds");Check(targets.Count==2,"normal fire randomly switches between two living players");Check(ringTimes.Count>=2,"at least two radial fireball skills");Check(ringTimes.Zip(ringTimes.Skip(1),(a,b)=>b-a).All(gap=>gap>=20&&gap<=40.3f),"radial skill cooldown stays in 20-40 seconds");Check(ringAngles.Count==12,"radial skill fires in twelve different directions");Check(!flyingBoss.UseHoldingItem(0,false),"Phoenix refuses melee attacks");report.Add("INFO radial times="+string.Join(",",ringTimes));CheckHitboxes();report.Add("FINISHED failures=0");}catch(Exception ex){report.Add("FAIL "+ex);}finally{if(player!=null)world.RemoveEntity(player.entityId,EnumRemoveEntityReason.Despawned);if(player2!=null)world.RemoveEntity(player2.entityId,EnumRemoveEntityReason.Despawned);foreach(var b in world.Entities.list.OfType<EntityPhoenixBoss>().ToArray())world.RemoveEntity(b.entityId,EnumRemoveEntityReason.Despawned);File.WriteAllLines(Folder+"/game-report.txt",report);Application.Quit();}return;}
if(!world.IsChunkAreaLoaded(new Vector3(8,80,8))&&Time.realtimeSinceStartup<deadline)return;phase=0;
  var spawned=new List<Entity>();bool oldMoon=world.isEventBloodMoon;
  try{
   Check(PhoenixRules.Tier(179999)==0&&PhoenixRules.Tier(180000)==16&&PhoenixRules.Tier(280000)==17&&PhoenixRules.Tier(380000)==18&&PhoenixRules.Tier(480000)==19,"T16-T19 exact boundaries; lower tiers excluded");
   Check(PhoenixRules.Night(8,4)==7&&PhoenixRules.Night(7,22)==7&&!PhoenixRules.InWindow(7,9),"night identity survives midnight; stale finale rejected");
   int[] health={80000000,150000000,260000000,450666667};
   for(int t=16;t<=19;t++){
    var boss=EntityFactory.CreateEntity(EntityClass.FromString("yfPhoenixBossT"+t),new Vector3(8,95,8)) as EntityPhoenixBoss;Check(boss!=null,"native Phoenix T"+t+" factory");spawned.Add(boss);world.SpawnEntityInWorld(boss);
    report.Add("INFO T"+t+" health="+boss.Health+" classMax="+boss.classMaxHealth+" statMax="+boss.Stats.Health.Max+" base="+boss.Stats.Health.BaseMax);if(t<19){var reference=(EntityAlive)EntityFactory.CreateEntity(EntityClass.FromString("AECTheExecutionerBossT"+(t+1)),new Vector3(8,95,8));report.Add("INFO reference next-tier health="+reference.Health);Check(boss.Health==reference.Health,"next-tier native health T"+t);UnityEngine.Object.Destroy(reference.gameObject);}else Check(boss.Health>=health[t-16]*.95f&&boss.Health<=health[t-16]*1.05f,"T19 extrapolated T20 health within native stat scaling");
    Check(boss.inventory.holdingItem.Actions[1] is ItemActionVomit,"native ranged flight action T"+t);
    var ammo=ItemClass.GetItem("yfPhoenixFireballT"+t).ItemClass;Check(ammo.Actions[1] is ItemActionProjectile,"native fire projectile T"+t);var explosion=((ItemActionProjectile)ammo.Actions[1]).Explosion;Check(explosion.Duration==30&&explosion.ParticleIndex==10&&explosion.BuffActions.Contains("buffBurningMolotov"),"native explosion parsed 30-second burning ground T"+t);
    Check(ammo.Properties.Classes["Action1"].Values["Buff"]=="buffBurningFlamingArrow","fire projectile ignites on hit T"+t);
    Check(int.Parse(ammo.Properties.Classes["Action1"].Classes["Explosion"].Values["BlockDamage"])>=6000,"high structure explosion damage T"+t);Check(ammo.Properties.Classes["Action1"].Classes["Explosion"].Values["Duration"]=="30"&&ammo.Properties.Classes["Action1"].Classes["Explosion"].Values["Buff"]=="buffBurningMolotov","30-second native fire area T"+t);
    if(t==16){var fire=GameManager.Instance.ExplosionClient(boss.position,Quaternion.identity,10,0,1f,0f,boss.entityId,new List<BlockChangeInfo>());Check(fire!=null,"native ground fire prefab instantiated");var life=fire.GetComponent<TemporaryObject>();Check(life!=null&&(float)AccessTools.Field(typeof(TemporaryObject),"life").GetValue(life)==30f,"client explosion hook sets 30 second fire lifetime");UnityEngine.Object.Destroy(fire);}
    world.RemoveEntity(boss.entityId,EnumRemoveEntityReason.Despawned);
   }
   string modPath=Path.Combine(PhoenixVisual.ModPath,"Resources/phoenix.unity3d");var bundle=AssetBundle.GetAllLoadedAssetBundles().FirstOrDefault(b=>b.Contains("Assets/Phoenix/PhoenixBoss.prefab"))??AssetBundle.LoadFromFile(modPath);
   var prefab=bundle.LoadAsset<GameObject>("Assets/Phoenix/PhoenixBoss.prefab");Check(prefab!=null&&prefab.GetComponentsInChildren<SkinnedMeshRenderer>().All(r=>r.sharedMaterials.All(m=>m.mainTexture!=null)),"game loads textured phoenix bundle");Check(prefab.GetComponentInChildren<Animation>().clip.length>3,"game loads flying animation");var fireBundle=AssetBundle.GetAllLoadedAssetBundles().FirstOrDefault(b=>b.Contains("Assets/Phoenix/PhoenixFireball.prefab"))??AssetBundle.LoadFromFile(Path.Combine(Path.GetDirectoryName(modPath),"phoenix-fire.unity3d"));Check(fireBundle!=null,"game loads fireball bundle");
   player=(EntityPlayer)EntityFactory.CreateEntity(EntityClass.FromString("playerMale"),new Vector3(8,80,8));player.MinEventContext.ItemValue=ItemValue.None;var h=new Harmony("yf.phoenix.qa");h.Patch(AccessTools.PropertyGetter(typeof(EntityPlayer),"gameStage"),prefix:new HarmonyMethod(typeof(PhoenixGameQA),nameof(Stage)));h.Patch(AccessTools.Method(typeof(PhoenixEncounter),"Key"),prefix:new HarmonyMethod(typeof(PhoenixGameQA),nameof(Identity)));h.Patch(AccessTools.Method(typeof(EntityPlayer),"OnUpdateEntity"),prefix:new HarmonyMethod(typeof(PhoenixGameQA),nameof(Bot)));h.Patch(AccessTools.Method(typeof(ProjectileMoveScript),"Fire"),postfix:new HarmonyMethod(typeof(PhoenixGameQA),nameof(Shot)));player.Stats.Health.BaseMax=1000000;player.Health=1000000;world.SpawnEntityInWorld(player);player2=(EntityPlayer)EntityFactory.CreateEntity(EntityClass.FromString("playerMale"),new Vector3(-8,80,8));player2.MinEventContext.ItemValue=ItemValue.None;player2.Stats.Health.BaseMax=1000000;player2.Health=1000000;world.SpawnEntityInWorld(player2);
   world.SetTime(GameUtils.DayTimeToWorldTime(7,22,0));Tick();AccessTools.Field(typeof(PhoenixEncounter),"state").SetValue(null,new EncounterState());world.isEventBloodMoon=true;Tick();Check(world.Entities.list.OfType<EntityPhoenixBoss>().Count()==0,"no finale while blood moon active");world.isEventBloodMoon=false;Tick();Check(!world.Entities.list.OfType<EntityPhoenixBoss>().Any(),"temporary night-time blood moon flag loss does not spawn boss");Check(((EncounterState)AccessTools.Field(typeof(PhoenixEncounter),"state").GetValue(null)).Deadline==0,"night-time flag loss does not start expiry timer");world.SetTime(GameUtils.DayTimeToWorldTime(8,world.DawnHour,0));Tick();var final=world.Entities.list.OfType<EntityPhoenixBoss>().ToArray();Check(final.Length==1,"blood moon end spawns exactly one phoenix");Tick();Tick();Check(world.Entities.list.OfType<EntityPhoenixBoss>().Count()==1,"repeated updates do not duplicate boss");AccessTools.Field(typeof(PhoenixEncounter),"world").SetValue(null,null);Tick();Check(world.Entities.list.OfType<EntityPhoenixBoss>().Count()==1,"journal reload does not duplicate boss");flyingBoss=final[0];initialPosition=flyingBoss.position;report.Add("INFO DebugStopEnemiesMoving="+GamePrefs.GetBool(EnumGamePrefs.DebugStopEnemiesMoving));GamePrefs.Set(EnumGamePrefs.DebugStopEnemiesMoving,false);h.Patch(AccessTools.Method(typeof(ItemActionVomit),"ExecuteAction"),prefix:new HarmonyMethod(typeof(PhoenixGameQA),nameof(Attempt)));h.Patch(AccessTools.Method(typeof(EntityVulture),"updateTasks"),postfix:new HarmonyMethod(typeof(PhoenixGameQA),nameof(AITick)));
   phase=2;deadline=Time.realtimeSinceStartup+85;report.Add("WAIT native flight and ranged combat");
  }catch(Exception ex){report.Add("FAIL "+ex);}
  finally{world.isEventBloodMoon=oldMoon;if(phase!=2){if(player!=null)world.RemoveEntity(player.entityId,EnumRemoveEntityReason.Despawned);if(player2!=null)world.RemoveEntity(player2.entityId,EnumRemoveEntityReason.Despawned);foreach(var e in spawned)if(world.GetEntity(e.entityId)!=null)world.RemoveEntity(e.entityId,EnumRemoveEntityReason.Despawned);File.WriteAllLines(Folder+"/game-report.txt",report);Application.Quit();}else File.WriteAllLines(Folder+"/game-report.txt",report);}
 }
}
