<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>PZAEC.Fishing</AssemblyName>
    <Deterministic>true</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>../../tools/Fishing/Integration/artifacts/build/</OutputPath>
    <GameRoot Condition="'$(GameRoot)' == ''">../../..</GameRoot>
    <GameManaged>$(GameRoot)/7DaysToDie_Data/Managed</GameManaged>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="GameAssemblies"><HintPath>$(GameManaged)/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp-firstpass"><HintPath>$(GameManaged)/Assembly-CSharp-firstpass.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="LogLibrary"><HintPath>$(GameManaged)/LogLibrary.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(GameManaged)/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="$(GameManaged)/UnityEngine.*.dll"><Private>false</Private></Reference>
    <Reference Include="InControl"><HintPath>$(GameManaged)/InControl.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(GameRoot)/Mods/0_TFP_Harmony/0Harmony.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
